### ISSUE TITLE
Inter project dependencies do not work with default configuration

### ISSUE THREAD

**Issue by ttho** [spring-projects/gradle-plugins#44]
Why are all deps from optional and provided excluded from the default configuration? This causes inter project dependencies not to pick up those. Example:

```
project(':impl') {
    dependencies {
        compile project(':api')
    }
}
```

This is the normal way to define inter project dependencies. I would expect that if ':api' defines dependencies in provided scope that they are also propagated to ':impl'. However, they won't.

A work-around is to explicitly reference the compile scope like here:

```
project(':impl') {
    dependencies {
        compile project(path: ':api', configuration: 'compile')
    }
}
```

But I like to know why you exclude provided deps from the default configuration in the first place.

**Comment by wilkinsona** [comment]
The propdeps plugin has [moved to the Spring Attic](https://github.com/spring-attic/propdeps-plugin) and is no longer maintained.
