### ISSUE TITLE
propdeps-plugin optional scope creates invalid pom

### ISSUE THREAD

**Issue by johnjaylward** [spring-projects/gradle-plugins#47]
maven declares the `<optional>` tag on a dependency to be a boolean(`<optional>true/false</optional>`), but the propdeps plugin instead creates an optional dependency as `<scope>optional</scope>` in the pom. I would expect the output of this to be something like:

```
<scope>compile</scope>
<optional>true</optional>
```

since it's optional, the actual `<scope>` tag value doesn't really matter, but I think compile would make sense most of the time.

I'm using gradle 2.1 and propdeps 0.0.7

see the maven document: http://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by wilkinsona** [comment]
The propdeps plugin has [moved to the Spring Attic](https://github.com/spring-attic/propdeps-plugin) and is no longer maintained.
