### ISSUE TITLE
Can't map custom scope when 'propdeps-maven' used

### ISSUE THREAD

**Issue by topr** [spring-projects/gradle-plugins#48]
When I'm using propdeps-maven, mapping of another custom configuration doesn't work well.

Something like below should do the job:

```
configurations {
    pu
    compile.extendsFrom pu
}

project.conf2ScopeMappings.addMapping(310, configurations.pu, 'compile')
```

However the last line Maven of `PropDepsMavenPlugin.apply()` method breaks something. Mapping is not propagated to both `project.install.repositories.mavenInstaller.pom.scopeMappings` and `uploadArchives.repositories.mavenDeployer.pom.scopeMappings` which results with generated pom without dependencies for my custom configuration.

It's enough to add, that commenting line `apply plugin: 'propdeps-maven'` fixes issues. Not sure is it a bug in gradle itself or some missusage of gradle API on the plugin side.

Two things worth of noticing:
1. I tried cooking simple example to recreate the issue (copy-pasted at the bottom). In the simple example only installer mapping doesn't contain my custom scope. However in the real, multi-module project, I'm currently working with, both installer and deployer mappings are affected. I'm not able to recreate deployer mappings issue for the sake of example though.
2. Calling pom {}.writeTo('file.xml') always shows correct pom with all necessary dependencies even though pom deployed with uploadArchives is missing my mapped dependencies.

In the following example there are also a few tasks added. Just run `gradle pI dI map` to see de differences between mappings which should be all the same. Speaking of my case (not the example below) output for the installer and deployer are the same including hashcode, but both are wrong as they are missing _pu_ scope. In the example below only installer is missing _pu_ scope.

``` groovy
buildscript {
    repositories {
        mavenCentral()
        maven { url 'http://repo.spring.io/plugins-release' }
    }
    dependencies {
        classpath 'org.springframework.build.gradle:propdeps-plugin:0.0.7'
    }
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'propdeps'
apply plugin: 'propdeps-maven'

configurations {
    pu
    compile.extendsFrom pu
}

group = 'test'
version = 0.1

project.conf2ScopeMappings.addMapping(310, configurations.pu, 'compile')

uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: 'file://localhost/c:/ubs/dev/work/tmp/m2')
        }
    }
}

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.3.6'
    runtime 'org.mongodb:mongo-java-driver:2.12.4'
    provided 'javax.servlet:javax.servlet-api:3.1.0'
    pu 'joda-time:joda-time:2.3'
    testCompile 'org.spockframework:spock-core:0.7-groovy-2.0'
}

task pomInstaller << {
    println '\nINSTALLER'
    printlnScope2ConfMapping(install.repositories.mavenInstaller.pom.scopeMappings)
}

task pomDeployer << {
    println '\nDEPLOYER'
    printlnScope2ConfMapping(uploadArchives.repositories.mavenDeployer.pom.scopeMappings)
}

task mappings << {
    println '\nMAPPINGS'
    printlnScope2ConfMapping(conf2ScopeMappings)
}

void printlnScope2ConfMapping(def conf2ScopeMappings) {
    println '-' * 50
    conf2ScopeMappings.mappings.each {
        println "\t$it.key.name - $it.value.configuration.name, $it.value.scope, $it.value.priority"
    }
    println '\nhashcode:' + conf2ScopeMappings.hashCode() + '\n\n'
}
```

**Comment by wilkinsona** [comment]
The propdeps plugin has [moved to the Spring Attic](https://github.com/spring-attic/propdeps-plugin) and is no longer maintained.
