### ISSUE TITLE
Plugin with id 'propdeps' not found.

### ISSUE THREAD

**Issue by olliefreeman** [spring-projects/gradle-plugins#49]
Hi, 

Using gradle 2.2 (and i'm not sure if this is why I'm getting the error), 
The entry into my gradle build file is returning the `Plugin with id 'propdeps' not found.` when gradle is run.
```
buildscript {
   repositories {
      maven {url artifactoryUrl}
      maven {url artifactoryPluginUrl }
   }
   dependencies {
      classpath 'org.springframework.build.gradle:propdeps-plugin:0.0.7'
   }
}

apply plugin: 'propdeps'
apply plugin: 'propdeps-maven'
apply plugin: 'propdeps-idea'
apply plugin: 'propdeps-eclipse'
```

The artifactory has the jar file for 0.0.7 and it is also in my local `.gradle/caches/modules-2` directory so I can't work out why gradle can't find the plugin.

Currently the only idea I have is its something to do with gradle 2.2 and the new plugin dsl even though I'm not using the new dsl.

**Comment by iMouseWu** [comment]
when I use gradle 1.12 and 2.2.1 and 2.3  I'm always getting the same error.
Then I do not know where I can find the 0.0.7jar
Maybe there is something wrong with with my network.

**Comment by takacsot** [comment]
Have you tried to add ` maven { url 'https://repo.spring.io/plugins-release' }` as described in the readme?

**Comment by olliefreeman** [comment]
im goping to close this as i think its all working, but I havent checked as I havent used the plugin in a while,
