### ISSUE TITLE
If a dependency is added to both compile and provided, it shows up only provided in IDE

### ISSUE THREAD

**Issue by apatrida** [spring-projects/gradle-plugins#50]
I have a base build that applies a dependency as provided to subprojects.  one subproject tries to override it by putting the same dependency into compile.  But in Intellij, the module shows up provided, and its transitive dependency compile.

**Comment by wilkinsona** [comment]
The propdeps plugin has [moved to the Spring Attic](https://github.com/spring-attic/propdeps-plugin) and is no longer maintained.
