### ISSUE TITLE
propdeps-plugin doesn't work with maven-publish and other plugins

### ISSUE THREAD

**Issue by praseodym** [spring-projects/gradle-plugins#52]
This plugin doesn't work with the maven-publish plugin, e.g. when `publishToMavenLocal` is used the generated POM file still contains any optional dependencies. It also doesn't work with the Bintray plugin.

I understand that this plugin can't modify behaviour of other plugins, but it would at least be nice to have this documented.

**Comment by wilkinsona** [comment]
There's more than one plugin managed in this repository. Which plugin are you referring to?

**Comment by praseodym** [comment]
I'm sorry, I was referring to the propdeps-plugin.

**Comment by madorb** [comment]
This seems like a really rather useful thing to have documented... any reason this can't be merged in? I landed here after a bunch of googling, this would have saved me some time :-)

**Comment by wilkinsona** [comment]
The propdeps plugin has [moved to the Spring Attic](https://github.com/spring-attic/propdeps-plugin) and is no longer maintained.
