### ISSUE TITLE
configuration with name 'provided' ... already exists

### ISSUE THREAD

**Issue by conve** [spring-projects/gradle-plugins#55]
With Grails 3.0.9, I'm getting this error doing 'grails war':

> Failed to apply plugin [id 'propdeps']
   > Cannot add a configuration with name 'provided' as a configuration with that name already exists.

**Comment by conve** [comment]
I think what's happening here is, provided was added by Grails 3.0.9, and the reason it wasn't working as-is for me was JspTagException had been moved from servlet-api to jsp-api.

**Comment by wilkinsona** [comment]
Thanks for following up
