### ISSUE TITLE
gradle cleanIdea eclipse ERROE

### ISSUE THREAD

**Issue by Benedict2** [spring-projects/gradle-plugins#57]
* What went wrong:
A problem occurred configuring root project 'spring'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not download gradle-sonarqube-plugin.jar (org.sonarqube.gradle:gradle-sonarqube-plugin:1.1)
      > Could not get resource 'https://plugins.gradle.org/m2/org/sonarqube/gradle/gradle-sonarqube-plugin/1.1/gradle-sonarqube-plugin-1.1.jar'.
         > Could not GET 'https://plugins.gradle.org/m2/org/sonarqube/gradle/gradle-sonarqube-plugin/1.1/gradle-sonarqube-plugin-1.1.jar'.
            > Connect to gradleware-plugins.s3.amazonaws.com:443 [gradleware-plugins.s3.amazonaws.com/54.231.48.152] failed: Connection timed out: connect

**Comment by wilkinsona** [comment]
This looks like a network connectivity problem to a bucket on S3. It doesn't appear to have anything to do with the plugins from this repository.
