### ISSUE TITLE
propdeps-plugin - Is provided scope still needed now that compileOnly exists?

### ISSUE THREAD

**Issue by mjustin** [spring-projects/gradle-plugins#58]
Gradle 2.12 introduced its own built-in [compileOnly](https://blog.gradle.org/introducing-compile-only-dependencies) dependency scope.  At an initial glance, this appears to be doing the same thing as "provided" properties in propdeps-plugin.  Does "provided" still need to exist in propdeps-plugin?

**Comment by rwinch** [comment]
@mjustin Thanks for the question. As far as I know compileOnly doesn't map to Maven Pom definition by default. This means we still need the mechanics of adding the configuration to the Maven Pom and ensuring that it is marked as provided.

If I'm wrong or there is some minor tweak we need to do, I'd love to hear about it.

**Comment by wilkinsona** [comment]
`compileOnly` dependencies also aren't included on the test classpath so you often have to declare the same dependency multiple times.

**Comment by bmuschko** [comment]
@wilkinsona FYI: The same aspect was brought up on the forum recently. [Mark Viera commented on it.](https://discuss.gradle.org/t/compileonly-dependencies-are-not-available-in-tests/15366/6)

**Comment by wilkinsona** [comment]
The propdeps plugin has [moved to the Spring Attic](https://github.com/spring-attic/propdeps-plugin) and is no longer maintained.
