### ISSUE TITLE
Gradle 4.0 Support

### ISSUE THREAD

**Issue by shammancer** [spring-projects/gradle-plugins#59]
As detailed in the Gradle 4.0 Release Notes there are a few [deprecations](https://docs.gradle.org/current/release-notes.html#deprecations)

Using the attached [demo project](https://github.com/spring-projects/gradle-plugins/files/1092380/demo.zip) you receive the following warning:

> Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0

**Comment by shammancer** [comment]
The demo project was created using the [Spring Initializr](https://start.spring.io/) defaults for a java gradle project.

**Comment by wilkinsona** [comment]
Spring Boot's Gradle plugin is managed in https://github.com/spring-projects/spring-boot. There are already issues for this: https://github.com/spring-projects/spring-boot/issues/9559 and https://github.com/spring-projects/spring-boot/issues/9516.
